# Site settings
baseurl = "http://janlaeuft.de/"
languageCode = "de"
title = "Jan läuft!"
theme = "running"
paginate = 5
disqusShortname = "janlaeuft"
[taxonomies]
  category = "categories"
# [permalinks]
#   blog = "/:year/:month/:title/"
