# Site settings
baseurl = "http://192.168.178.30:8080/"
languageCode = "en"
title = "foo bar"
theme = "running"
paginate = 3
disqusShortname = "janlaeuft"
[taxonomies]
  category = "categories"
# [permalinks]
#   blog = "/:year/:month/:title/"
