# Site settings
baseurl = "http://janlaeuft.de/"
languageCode = "en"
title = "foo bar"
theme = "running"
paginate = 3
disqusShortname = "janlaeuft"
[taxonomies]
  category = "categories"
# [permalinks]
#   blog = "/:year/:month/:title/"
