# Site settings
baseurl = "http://localhost:8080/"
languageCode = "en"
title = "foo bar"
theme = "cactus"
[taxonomies]
  categories = "category"
# paginate = 2
[permalinks]
  blog = "/:year/:month/:title/"
